### ISSUE TITLE
The transcription process is going to start soon, please wait ...

### ISSUE THREAD

**Issue by pedrogk** [aws-samples/amazon-transcribe-news-media-analysis#72]
Hello! Thank you for creating this solution. 

I am trying to use this to generate the transcription of live streaming video and I am getting a message "The transcription process is going to start soon, please wait".

- I tried first with a YouTube live video and when going to the Watch URL I can see the video, but instead of the transmission I get that error message.
- Then I tried with a m3u8 url and the result is the same.

![image](https://user-images.githubusercontent.com/417135/121854646-0e3f2480-ccb8-11eb-97d1-9973cf9f5d43.png)
![image](https://user-images.githubusercontent.com/417135/121854539-e6e85780-ccb7-11eb-9cca-aa19a60d1e46.png)

What do you think is happening? Any troubleshooting or debugging tips?

Thanks!

**Comment by pedrogk** [comment]
Checking out the logs, under /ecs/transcriber I see
 
```Exception in thread "main" java.lang.NoSuchMethodError: org.apache.logging.log4j.util.PropertiesUtil.getStringProperty([Ljava/lang/String;Ljava/lang/String;Lorg/apache/logging/log4j/util/Supplier;)Ljava/lang/String;
...
...
at com.amazonaws.transcriber.App.<clinit>(App.java:40)
```

You think this has something to do?

**Comment by svozza** [comment]
I wonder if it's something to do with this change: https://github.com/aws-samples/amazon-transcribe-news-media-analysis/pull/66. Try rolling back to the old version and see if that fixes it. You'll need to rebuild the container and push it to ECR.

**Comment by matteofigus** [comment]
Closing because we haven't heard anything back so we assume it's fixed.
